name: shape_devel
run-name: Setting up the shape_devel database
on: [push]
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
    - name: Test Output
      run: |
        echo "PREX=true" >> $env:GITHUB_ENV
  connect-remote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run a sample SQL on remote
      run: mysql -h ${{ secrets.DB_HOSTNAME }} --port 1433 -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "source test_for_sql/hawthorn_script.sql";
