name: sql-test
run-name: ${{ github.actor }} is testing SQL
on: [push]
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
    - name: Test Output
      run: echo "here is a test" 
  connect-remote:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: Test_DB
      DB_USER: sa
      DB_PASSWORD: 123
    steps:
    - uses: actions/checkout@v3   
    - name: Run a sample SQL on remote
      run: mysql -h ${{ secrets.DB_HOSTNAME }} --port 3306 -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -e "source test_for_sql/hawthorn_script.sql"
