name: shape_devel
run-name: Setting up the shape_devel database
on: [push]
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
    - name: Test Output
      run: echo "Here is a test"
  connect-remote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run a sample SQL on remote
      run: mysql --host=SUKHRAM-DOTNET\\SOFTSYSSOL --user=sa --password=sukh@123 -e "source hawthorn/hawthorn_script.sql";
